In [50]:
import numpy as np

## Basic Numpy Arrays

In [51]:
a = np.array([1, 2, 3, 4])

In [52]:
a.dtype

dtype('int64')

In [53]:
a[0:]

array([1, 2, 3, 4])

In [54]:
a[1:3]

array([2, 3])

In [56]:
a[0:-1]

array([1, 2, 3])

In [57]:
a[::2]

array([1, 3])

In [61]:
b = np.array([0, .5, 1.5, 2])

In [62]:
b

array([0. , 0.5, 1.5, 2. ])

In [63]:
b.dtype

dtype('float64')

In [64]:
a

array([1, 2, 3, 4])

In [65]:
b

array([0. , 0.5, 1.5, 2. ])

In [66]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [67]:
c = np.array(['a', 'b', 'c'])

In [68]:
c.dtype

dtype('<U1')

## Dimensions and shapes

In [69]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [70]:
A.shape

(2, 3)

In [71]:
A.ndim

2

In [72]:
A.size

6

In [73]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [74]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [75]:
B.shape

(2, 2, 3)

In [76]:
B.ndim

3

In [77]:
B.size

12

## Indexing and Slicing of Matrices

In [78]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [79]:
A[1]

array([4, 5, 6])

In [80]:
A[1][0]

np.int64(4)

In [ ]:
# A[d1, d2, d3, d4]

In [81]:
A[1, 0]

np.int64(4)

In [82]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [84]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [85]:
A[:2, 2:]

array([[3],
       [6]])

In [87]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [88]:
A[1] = np.array([10, 10, 10])

In [89]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [90]:
A[2] = 99

In [91]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary statistics

In [92]:
a = np.array([1, 2, 3, 4])

In [93]:
a.sum()

np.int64(10)

In [94]:
a.mean()

np.float64(2.5)

In [95]:
a.std()

np.float64(1.118033988749895)

In [96]:
a.var()

np.float64(1.25)

In [97]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [98]:
A.sum()

np.int64(45)

In [99]:
A.mean()

np.float64(5.0)

In [100]:
A.std()

np.float64(2.581988897471611)

In [101]:
A.sum(axis=0)

array([12, 15, 18])

In [102]:
A.sum(axis=1)

array([ 6, 15, 24])

In [103]:
A.mean(axis=0)

array([4., 5., 6.])

In [104]:
A.mean(axis=1)

array([2., 5., 8.])

In [105]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [106]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Broadcasting and Vectorized operations

In [107]:
a = np.arange(4)

In [108]:
a

array([0, 1, 2, 3])

In [109]:
a + 10

array([10, 11, 12, 13])

In [110]:
a * 10

array([ 0, 10, 20, 30])

In [111]:
a

array([0, 1, 2, 3])

In [112]:
a += 100

In [113]:
a

array([100, 101, 102, 103])

In [114]:
a = np.arange(4)

In [115]:
a

array([0, 1, 2, 3])

In [116]:
b = np.array([10, 10, 10, 10])

In [117]:
b

array([10, 10, 10, 10])

In [118]:
a + b

array([10, 11, 12, 13])

In [119]:
a * b

array([ 0, 10, 20, 30])

## Boolean arrays


In [120]:
a = np.arange(4)

In [121]:
a

array([0, 1, 2, 3])

In [122]:
a[0], a[-1]

(np.int64(0), np.int64(3))

In [123]:
a[[0, -1]]

array([0, 3])

In [124]:
a[[True, False, False, True]]

array([0, 3])

In [125]:
a

array([0, 1, 2, 3])

In [126]:
a >= 2

array([False, False,  True,  True])

In [127]:
a[a >= 2]

array([2, 3])

In [128]:
a.mean()

np.float64(1.5)

In [129]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~(a > a.mean())]

In [ ]:
a[(a == 0) | (a == 1)]

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [ ]:
A > 30

In [ ]:
A[A > 30]

## Linear Algebra

In [130]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [131]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [132]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [133]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [134]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [135]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Int, floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

In [ ]:
np.dtype(float).itemsize

### Lists are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

### And performance is also important

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

In [ ]:
%time sum([x ** 2 for x in l])

## Useful Numpy functions

In [ ]:
### `random` 

np.random.random(size=2)

In [ ]:
np.random.normal(size=2)

In [ ]:
np.random.rand(2, 4)

### `arange`

In [ ]:
np.arange(10)

In [ ]:
np.arange(5, 10)

In [ ]:
np.arange(0, 1, .1)

### `reshape`

In [ ]:
np.arange(10).reshape(2, 5)

In [ ]:
np.arange(10).reshape(5, 2)

### `linspace`

In [ ]:
np.linspace(0, 1, 5)

In [ ]:
np.linspace(0, 1, 20)

In [ ]:
np.linspace(0, 1, 20, False)

### `zeros`, `ones`, `empty`

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3, 3))

In [ ]:
np.zeros((3, 3), dtype=np.int)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3, 3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2, 2))

### `identity` and `eye`

In [ ]:
np.identity(3)

In [ ]:
np.eye(3, 3)

In [ ]:
np.eye(8, 4)

In [ ]:
np.eye(8, 4, k=1)

In [ ]:
np.eye(8, 4, k=-3)